name: tinder_clone
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  easy_localization: ^3.0.5
  go_router: ^13.2.1
  flutter_bloc: ^8.1.4
  equatable: ^2.0.5
  dio: ^5.4.1
  get_it: ^7.6.7
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  dartz: ^0.10.1
  get_cli: ^1.8.1
  easy_localization_loader: 2.0.0
  flutter_screenutil: ^5.9.3
  google_fonts: ^6.2.1
  auto_size_text: ^3.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  
  assets:
    - assets/language/
    - assets/icon/

 
